import './globals.css'
import { Open_Sans, Roboto_Mono, Cherry_Bomb_One } from 'next/font/google'

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-opensans',
})

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

const cherryBombOne = Cherry_Bomb_One({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cherry-bomb-one',
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${robotoMono.variable} ${cherryBombOne.variable} font-sans`}
    >
      <body>{children}</body>
    </html>
  )
}
